import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Vaults from 'src/vaults';
import CurrentUser from 'src/currentUser';
import CurrentUserRisk from 'src/currentUserRisk';

const IS_RISK = true;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!IS_RISK &&
        <>
          <h1>Client Dashboard</h1>
          <CurrentUser />
          <Vaults />
        </>
      }
      {IS_RISK &&
        <>
          <h1>RISK Dashboard</h1>
          <CurrentUserRisk />
        </>
      }
    </div>
  );
};

export default Home;
