import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { useQuery } from '@apollo/client';
import TEST_QUERY from './TestQuery.graphql';

const Home: NextPage = () => {
  const { data, loading, error } = useQuery(TEST_QUERY);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Countries</h1>
      <ul>
        {data?.countries.map((country: { name: string }) => (
          <li key={country.name}>{country.name}</li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
